// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.domain;

import org.springframework.beans.factory.annotation.Configurable;
import tr.edu.metu.ii.sm504.domain.AuditableEntity;

privileged aspect AuditableEntity_Roo_Configurable {
    
    declare @type: AuditableEntity: @Configurable;
    
}
