// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.jsf;

import java.io.Serializable;
import tr.edu.metu.ii.sm504.jsf.ActivityBean;

privileged aspect ActivityBean_Roo_Serializable {
    
    declare parents: ActivityBean implements Serializable;
    
    private static final long ActivityBean.serialVersionUID = 1L;
    
}
