// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.jsf;

import java.io.Serializable;
import tr.edu.metu.ii.sm504.jsf.PermissionBean;

privileged aspect PermissionBean_Roo_Serializable {
    
    declare parents: PermissionBean implements Serializable;
    
    private static final long PermissionBean.serialVersionUID = 1L;
    
}
