// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.jsf;

import java.io.Serializable;
import tr.edu.metu.ii.sm504.jsf.RoleBean;

privileged aspect RoleBean_Roo_Serializable {
    
    declare parents: RoleBean implements Serializable;
    
    private static final long RoleBean.serialVersionUID = 1L;
    
}
