// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.jsf;

import java.io.Serializable;
import tr.edu.metu.ii.sm504.jsf.StudentBean;

privileged aspect StudentBean_Roo_Serializable {
    
    declare parents: StudentBean implements Serializable;
    
    private static final long StudentBean.serialVersionUID = 1L;
    
}
