// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import tr.edu.metu.ii.sm504.domain.Assistant;
import tr.edu.metu.ii.sm504.domain.AssistantDataOnDemand;
import tr.edu.metu.ii.sm504.domain.User;
import tr.edu.metu.ii.sm504.domain.UserDataOnDemand;

privileged aspect AssistantDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AssistantDataOnDemand: @Component;
    
    private Random AssistantDataOnDemand.rnd = new SecureRandom();
    
    private List<Assistant> AssistantDataOnDemand.data;
    
    @Autowired
    private UserDataOnDemand AssistantDataOnDemand.userDataOnDemand;
    
    public Assistant AssistantDataOnDemand.getNewTransientAssistant(int index) {
        Assistant obj = new Assistant();
        setCreatedBy(obj, index);
        setCreationTime(obj, index);
        setUpdateTime(obj, index);
        setUpdatedBy(obj, index);
        setUser(obj, index);
        return obj;
    }
    
    public void AssistantDataOnDemand.setCreatedBy(Assistant obj, int index) {
        User createdBy = userDataOnDemand.getRandomUser();
        obj.setCreatedBy(createdBy);
    }
    
    public void AssistantDataOnDemand.setCreationTime(Assistant obj, int index) {
        Date creationTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreationTime(creationTime);
    }
    
    public void AssistantDataOnDemand.setUpdateTime(Assistant obj, int index) {
        Date updateTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdateTime(updateTime);
    }
    
    public void AssistantDataOnDemand.setUpdatedBy(Assistant obj, int index) {
        User updatedBy = userDataOnDemand.getRandomUser();
        obj.setUpdatedBy(updatedBy);
    }
    
    public void AssistantDataOnDemand.setUser(Assistant obj, int index) {
        User user = userDataOnDemand.getRandomUser();
        obj.setUser(user);
    }
    
    public Assistant AssistantDataOnDemand.getSpecificAssistant(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Assistant obj = data.get(index);
        Long id = obj.getId();
        return Assistant.findAssistant(id);
    }
    
    public Assistant AssistantDataOnDemand.getRandomAssistant() {
        init();
        Assistant obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Assistant.findAssistant(id);
    }
    
    public boolean AssistantDataOnDemand.modifyAssistant(Assistant obj) {
        return false;
    }
    
    public void AssistantDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Assistant.findAssistantEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Assistant' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Assistant>();
        for (int i = 0; i < 10; i++) {
            Assistant obj = getNewTransientAssistant(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
