// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.domain;

import javax.persistence.Entity;
import javax.persistence.Table;
import tr.edu.metu.ii.sm504.domain.ProjectTeam;

privileged aspect ProjectTeam_Roo_Jpa_Entity {
    
    declare @type: ProjectTeam: @Entity;
    
    declare @type: ProjectTeam: @Table(name = "PROJECT_TEAM");
    
}
