// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import tr.edu.metu.ii.sm504.domain.Instructor;
import tr.edu.metu.ii.sm504.domain.InstructorDataOnDemand;
import tr.edu.metu.ii.sm504.domain.User;
import tr.edu.metu.ii.sm504.domain.UserDataOnDemand;

privileged aspect InstructorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InstructorDataOnDemand: @Component;
    
    private Random InstructorDataOnDemand.rnd = new SecureRandom();
    
    private List<Instructor> InstructorDataOnDemand.data;
    
    @Autowired
    private UserDataOnDemand InstructorDataOnDemand.userDataOnDemand;
    
    public Instructor InstructorDataOnDemand.getNewTransientInstructor(int index) {
        Instructor obj = new Instructor();
        setCreatedBy(obj, index);
        setCreationTime(obj, index);
        setUpdateTime(obj, index);
        setUpdatedBy(obj, index);
        setUser(obj, index);
        return obj;
    }
    
    public void InstructorDataOnDemand.setCreatedBy(Instructor obj, int index) {
        User createdBy = userDataOnDemand.getRandomUser();
        obj.setCreatedBy(createdBy);
    }
    
    public void InstructorDataOnDemand.setCreationTime(Instructor obj, int index) {
        Date creationTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreationTime(creationTime);
    }
    
    public void InstructorDataOnDemand.setUpdateTime(Instructor obj, int index) {
        Date updateTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdateTime(updateTime);
    }
    
    public void InstructorDataOnDemand.setUpdatedBy(Instructor obj, int index) {
        User updatedBy = userDataOnDemand.getRandomUser();
        obj.setUpdatedBy(updatedBy);
    }
    
    public void InstructorDataOnDemand.setUser(Instructor obj, int index) {
        User user = userDataOnDemand.getRandomUser();
        obj.setUser(user);
    }
    
    public Instructor InstructorDataOnDemand.getSpecificInstructor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Instructor obj = data.get(index);
        Long id = obj.getId();
        return Instructor.findInstructor(id);
    }
    
    public Instructor InstructorDataOnDemand.getRandomInstructor() {
        init();
        Instructor obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Instructor.findInstructor(id);
    }
    
    public boolean InstructorDataOnDemand.modifyInstructor(Instructor obj) {
        return false;
    }
    
    public void InstructorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Instructor.findInstructorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Instructor' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Instructor>();
        for (int i = 0; i < 10; i++) {
            Instructor obj = getNewTransientInstructor(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
