// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import tr.edu.metu.ii.sm504.domain.ProjectTeam;
import tr.edu.metu.ii.sm504.domain.ProjectTeamDataOnDemand;
import tr.edu.metu.ii.sm504.domain.Review;
import tr.edu.metu.ii.sm504.domain.ReviewDataOnDemand;
import tr.edu.metu.ii.sm504.domain.Submission;
import tr.edu.metu.ii.sm504.domain.SubmissionActivity;
import tr.edu.metu.ii.sm504.domain.SubmissionActivityDataOnDemand;
import tr.edu.metu.ii.sm504.domain.SubmissionDataOnDemand;
import tr.edu.metu.ii.sm504.domain.User;
import tr.edu.metu.ii.sm504.domain.UserDataOnDemand;

privileged aspect ReviewDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReviewDataOnDemand: @Component;
    
    private Random ReviewDataOnDemand.rnd = new SecureRandom();
    
    private List<Review> ReviewDataOnDemand.data;
    
    @Autowired
    private UserDataOnDemand ReviewDataOnDemand.userDataOnDemand;
    
    @Autowired
    private ProjectTeamDataOnDemand ReviewDataOnDemand.projectTeamDataOnDemand;
    
    @Autowired
    private SubmissionDataOnDemand ReviewDataOnDemand.submissionDataOnDemand;
    
    @Autowired
    private SubmissionActivityDataOnDemand ReviewDataOnDemand.submissionActivityDataOnDemand;
    
    public Review ReviewDataOnDemand.getNewTransientReview(int index) {
        Review obj = new Review();
        setCreatedBy(obj, index);
        setCreationTime(obj, index);
        setProjectTeam(obj, index);
        setSubmission(obj, index);
        setSubmissionActivity(obj, index);
        setUpdateTime(obj, index);
        setUpdatedBy(obj, index);
        return obj;
    }
    
    public void ReviewDataOnDemand.setCreatedBy(Review obj, int index) {
        User createdBy = userDataOnDemand.getRandomUser();
        obj.setCreatedBy(createdBy);
    }
    
    public void ReviewDataOnDemand.setCreationTime(Review obj, int index) {
        Date creationTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreationTime(creationTime);
    }
    
    public void ReviewDataOnDemand.setProjectTeam(Review obj, int index) {
        ProjectTeam projectTeam = projectTeamDataOnDemand.getRandomProjectTeam();
        obj.setProjectTeam(projectTeam);
    }
    
    public void ReviewDataOnDemand.setSubmission(Review obj, int index) {
        Submission submission = submissionDataOnDemand.getRandomSubmission();
        obj.setSubmission(submission);
    }
    
    public void ReviewDataOnDemand.setSubmissionActivity(Review obj, int index) {
        SubmissionActivity submissionActivity = submissionActivityDataOnDemand.getRandomSubmissionActivity();
        obj.setSubmissionActivity(submissionActivity);
    }
    
    public void ReviewDataOnDemand.setUpdateTime(Review obj, int index) {
        Date updateTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdateTime(updateTime);
    }
    
    public void ReviewDataOnDemand.setUpdatedBy(Review obj, int index) {
        User updatedBy = userDataOnDemand.getRandomUser();
        obj.setUpdatedBy(updatedBy);
    }
    
    public Review ReviewDataOnDemand.getSpecificReview(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Review obj = data.get(index);
        Long id = obj.getId();
        return Review.findReview(id);
    }
    
    public Review ReviewDataOnDemand.getRandomReview() {
        init();
        Review obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Review.findReview(id);
    }
    
    public boolean ReviewDataOnDemand.modifyReview(Review obj) {
        return false;
    }
    
    public void ReviewDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Review.findReviewEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Review' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Review>();
        for (int i = 0; i < 10; i++) {
            Review obj = getNewTransientReview(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
