// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import tr.edu.metu.ii.sm504.domain.Role;
import tr.edu.metu.ii.sm504.domain.RoleDataOnDemand;
import tr.edu.metu.ii.sm504.domain.User;
import tr.edu.metu.ii.sm504.domain.UserDataOnDemand;

privileged aspect RoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RoleDataOnDemand: @Component;
    
    private Random RoleDataOnDemand.rnd = new SecureRandom();
    
    private List<Role> RoleDataOnDemand.data;
    
    @Autowired
    private UserDataOnDemand RoleDataOnDemand.userDataOnDemand;
    
    public Role RoleDataOnDemand.getNewTransientRole(int index) {
        Role obj = new Role();
        setCreatedBy(obj, index);
        setCreationTime(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        setUpdateTime(obj, index);
        setUpdatedBy(obj, index);
        return obj;
    }
    
    public void RoleDataOnDemand.setCreatedBy(Role obj, int index) {
        User createdBy = userDataOnDemand.getRandomUser();
        obj.setCreatedBy(createdBy);
    }
    
    public void RoleDataOnDemand.setCreationTime(Role obj, int index) {
        Date creationTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreationTime(creationTime);
    }
    
    public void RoleDataOnDemand.setDescription(Role obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void RoleDataOnDemand.setName(Role obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void RoleDataOnDemand.setUpdateTime(Role obj, int index) {
        Date updateTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdateTime(updateTime);
    }
    
    public void RoleDataOnDemand.setUpdatedBy(Role obj, int index) {
        User updatedBy = userDataOnDemand.getRandomUser();
        obj.setUpdatedBy(updatedBy);
    }
    
    public Role RoleDataOnDemand.getSpecificRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Role obj = data.get(index);
        Long id = obj.getId();
        return Role.findRole(id);
    }
    
    public Role RoleDataOnDemand.getRandomRole() {
        init();
        Role obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Role.findRole(id);
    }
    
    public boolean RoleDataOnDemand.modifyRole(Role obj) {
        return false;
    }
    
    public void RoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Role.findRoleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Role' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Role>();
        for (int i = 0; i < 10; i++) {
            Role obj = getNewTransientRole(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
