// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import tr.edu.metu.ii.sm504.domain.Schedule;
import tr.edu.metu.ii.sm504.domain.ScheduleDataOnDemand;
import tr.edu.metu.ii.sm504.domain.ScheduleIntegrationTest;

privileged aspect ScheduleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ScheduleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ScheduleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ScheduleIntegrationTest: @Transactional;
    
    @Autowired
    private ScheduleDataOnDemand ScheduleIntegrationTest.dod;
    
    @Test
    public void ScheduleIntegrationTest.testCountSchedules() {
        Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", dod.getRandomSchedule());
        long count = Schedule.countSchedules();
        Assert.assertTrue("Counter for 'Schedule' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ScheduleIntegrationTest.testFindSchedule() {
        Schedule obj = dod.getRandomSchedule();
        Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Schedule' failed to provide an identifier", id);
        obj = Schedule.findSchedule(id);
        Assert.assertNotNull("Find method for 'Schedule' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Schedule' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ScheduleIntegrationTest.testFindAllSchedules() {
        Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", dod.getRandomSchedule());
        long count = Schedule.countSchedules();
        Assert.assertTrue("Too expensive to perform a find all test for 'Schedule', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Schedule> result = Schedule.findAllSchedules();
        Assert.assertNotNull("Find all method for 'Schedule' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Schedule' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ScheduleIntegrationTest.testFindScheduleEntries() {
        Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", dod.getRandomSchedule());
        long count = Schedule.countSchedules();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Schedule> result = Schedule.findScheduleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Schedule' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Schedule' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ScheduleIntegrationTest.testFlush() {
        Schedule obj = dod.getRandomSchedule();
        Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Schedule' failed to provide an identifier", id);
        obj = Schedule.findSchedule(id);
        Assert.assertNotNull("Find method for 'Schedule' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySchedule(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Schedule' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ScheduleIntegrationTest.testMergeUpdate() {
        Schedule obj = dod.getRandomSchedule();
        Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Schedule' failed to provide an identifier", id);
        obj = Schedule.findSchedule(id);
        boolean modified =  dod.modifySchedule(obj);
        Integer currentVersion = obj.getVersion();
        Schedule merged = (Schedule)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Schedule' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ScheduleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", dod.getRandomSchedule());
        Schedule obj = dod.getNewTransientSchedule(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Schedule' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Schedule' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Schedule' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ScheduleIntegrationTest.testRemove() {
        Schedule obj = dod.getRandomSchedule();
        Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Schedule' failed to provide an identifier", id);
        obj = Schedule.findSchedule(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Schedule' with identifier '" + id + "'", Schedule.findSchedule(id));
    }
    
}
