// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import tr.edu.metu.ii.sm504.domain.Course;
import tr.edu.metu.ii.sm504.domain.CourseDataOnDemand;
import tr.edu.metu.ii.sm504.domain.ProjectTeam;
import tr.edu.metu.ii.sm504.domain.ProjectTeamDataOnDemand;
import tr.edu.metu.ii.sm504.domain.Student;
import tr.edu.metu.ii.sm504.domain.StudentDataOnDemand;
import tr.edu.metu.ii.sm504.domain.User;
import tr.edu.metu.ii.sm504.domain.UserDataOnDemand;

privileged aspect StudentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StudentDataOnDemand: @Component;
    
    private Random StudentDataOnDemand.rnd = new SecureRandom();
    
    private List<Student> StudentDataOnDemand.data;
    
    @Autowired
    private CourseDataOnDemand StudentDataOnDemand.courseDataOnDemand;
    
    @Autowired
    private UserDataOnDemand StudentDataOnDemand.userDataOnDemand;
    
    @Autowired
    private ProjectTeamDataOnDemand StudentDataOnDemand.projectTeamDataOnDemand;
    
    public Student StudentDataOnDemand.getNewTransientStudent(int index) {
        Student obj = new Student();
        setCourse(obj, index);
        setCreatedBy(obj, index);
        setCreationTime(obj, index);
        setProjectTeam(obj, index);
        setStudentNumber(obj, index);
        setUpdateTime(obj, index);
        setUpdatedBy(obj, index);
        setUser(obj, index);
        return obj;
    }
    
    public void StudentDataOnDemand.setCourse(Student obj, int index) {
        Course course = courseDataOnDemand.getRandomCourse();
        obj.setCourse(course);
    }
    
    public void StudentDataOnDemand.setCreatedBy(Student obj, int index) {
        User createdBy = userDataOnDemand.getRandomUser();
        obj.setCreatedBy(createdBy);
    }
    
    public void StudentDataOnDemand.setCreationTime(Student obj, int index) {
        Date creationTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreationTime(creationTime);
    }
    
    public void StudentDataOnDemand.setProjectTeam(Student obj, int index) {
        ProjectTeam projectTeam = projectTeamDataOnDemand.getRandomProjectTeam();
        obj.setProjectTeam(projectTeam);
    }
    
    public void StudentDataOnDemand.setStudentNumber(Student obj, int index) {
        String studentNumber = "studentNumber_" + index;
        obj.setStudentNumber(studentNumber);
    }
    
    public void StudentDataOnDemand.setUpdateTime(Student obj, int index) {
        Date updateTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdateTime(updateTime);
    }
    
    public void StudentDataOnDemand.setUpdatedBy(Student obj, int index) {
        User updatedBy = userDataOnDemand.getRandomUser();
        obj.setUpdatedBy(updatedBy);
    }
    
    public void StudentDataOnDemand.setUser(Student obj, int index) {
        User user = userDataOnDemand.getRandomUser();
        obj.setUser(user);
    }
    
    public Student StudentDataOnDemand.getSpecificStudent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Student obj = data.get(index);
        Long id = obj.getId();
        return Student.findStudent(id);
    }
    
    public Student StudentDataOnDemand.getRandomStudent() {
        init();
        Student obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Student.findStudent(id);
    }
    
    public boolean StudentDataOnDemand.modifyStudent(Student obj) {
        return false;
    }
    
    public void StudentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Student.findStudentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Student' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Student>();
        for (int i = 0; i < 10; i++) {
            Student obj = getNewTransientStudent(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
