// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import tr.edu.metu.ii.sm504.domain.Activity;
import tr.edu.metu.ii.sm504.domain.ActivityDataOnDemand;
import tr.edu.metu.ii.sm504.domain.SubmissionActivity;
import tr.edu.metu.ii.sm504.domain.SubmissionActivityDataOnDemand;
import tr.edu.metu.ii.sm504.domain.User;
import tr.edu.metu.ii.sm504.domain.UserDataOnDemand;

privileged aspect SubmissionActivityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SubmissionActivityDataOnDemand: @Component;
    
    private Random SubmissionActivityDataOnDemand.rnd = new SecureRandom();
    
    private List<SubmissionActivity> SubmissionActivityDataOnDemand.data;
    
    @Autowired
    private ActivityDataOnDemand SubmissionActivityDataOnDemand.activityDataOnDemand;
    
    @Autowired
    private UserDataOnDemand SubmissionActivityDataOnDemand.userDataOnDemand;
    
    public SubmissionActivity SubmissionActivityDataOnDemand.getNewTransientSubmissionActivity(int index) {
        SubmissionActivity obj = new SubmissionActivity();
        setActivity(obj, index);
        setCreatedBy(obj, index);
        setCreationTime(obj, index);
        setUpdateTime(obj, index);
        setUpdatedBy(obj, index);
        return obj;
    }
    
    public void SubmissionActivityDataOnDemand.setActivity(SubmissionActivity obj, int index) {
        Activity activity = activityDataOnDemand.getRandomActivity();
        obj.setActivity(activity);
    }
    
    public void SubmissionActivityDataOnDemand.setCreatedBy(SubmissionActivity obj, int index) {
        User createdBy = userDataOnDemand.getRandomUser();
        obj.setCreatedBy(createdBy);
    }
    
    public void SubmissionActivityDataOnDemand.setCreationTime(SubmissionActivity obj, int index) {
        Date creationTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreationTime(creationTime);
    }
    
    public void SubmissionActivityDataOnDemand.setUpdateTime(SubmissionActivity obj, int index) {
        Date updateTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdateTime(updateTime);
    }
    
    public void SubmissionActivityDataOnDemand.setUpdatedBy(SubmissionActivity obj, int index) {
        User updatedBy = userDataOnDemand.getRandomUser();
        obj.setUpdatedBy(updatedBy);
    }
    
    public SubmissionActivity SubmissionActivityDataOnDemand.getSpecificSubmissionActivity(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SubmissionActivity obj = data.get(index);
        Long id = obj.getId();
        return SubmissionActivity.findSubmissionActivity(id);
    }
    
    public SubmissionActivity SubmissionActivityDataOnDemand.getRandomSubmissionActivity() {
        init();
        SubmissionActivity obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SubmissionActivity.findSubmissionActivity(id);
    }
    
    public boolean SubmissionActivityDataOnDemand.modifySubmissionActivity(SubmissionActivity obj) {
        return false;
    }
    
    public void SubmissionActivityDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SubmissionActivity.findSubmissionActivityEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SubmissionActivity' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SubmissionActivity>();
        for (int i = 0; i < 10; i++) {
            SubmissionActivity obj = getNewTransientSubmissionActivity(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
