// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tr.edu.metu.ii.sm504.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import tr.edu.metu.ii.sm504.domain.Submission;
import tr.edu.metu.ii.sm504.domain.SubmissionDataOnDemand;
import tr.edu.metu.ii.sm504.domain.SubmissionIntegrationTest;

privileged aspect SubmissionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SubmissionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SubmissionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SubmissionIntegrationTest: @Transactional;
    
    @Autowired
    private SubmissionDataOnDemand SubmissionIntegrationTest.dod;
    
    @Test
    public void SubmissionIntegrationTest.testCountSubmissions() {
        Assert.assertNotNull("Data on demand for 'Submission' failed to initialize correctly", dod.getRandomSubmission());
        long count = Submission.countSubmissions();
        Assert.assertTrue("Counter for 'Submission' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SubmissionIntegrationTest.testFindSubmission() {
        Submission obj = dod.getRandomSubmission();
        Assert.assertNotNull("Data on demand for 'Submission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Submission' failed to provide an identifier", id);
        obj = Submission.findSubmission(id);
        Assert.assertNotNull("Find method for 'Submission' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Submission' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SubmissionIntegrationTest.testFindAllSubmissions() {
        Assert.assertNotNull("Data on demand for 'Submission' failed to initialize correctly", dod.getRandomSubmission());
        long count = Submission.countSubmissions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Submission', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Submission> result = Submission.findAllSubmissions();
        Assert.assertNotNull("Find all method for 'Submission' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Submission' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SubmissionIntegrationTest.testFindSubmissionEntries() {
        Assert.assertNotNull("Data on demand for 'Submission' failed to initialize correctly", dod.getRandomSubmission());
        long count = Submission.countSubmissions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Submission> result = Submission.findSubmissionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Submission' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Submission' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SubmissionIntegrationTest.testFlush() {
        Submission obj = dod.getRandomSubmission();
        Assert.assertNotNull("Data on demand for 'Submission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Submission' failed to provide an identifier", id);
        obj = Submission.findSubmission(id);
        Assert.assertNotNull("Find method for 'Submission' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySubmission(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Submission' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SubmissionIntegrationTest.testMergeUpdate() {
        Submission obj = dod.getRandomSubmission();
        Assert.assertNotNull("Data on demand for 'Submission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Submission' failed to provide an identifier", id);
        obj = Submission.findSubmission(id);
        boolean modified =  dod.modifySubmission(obj);
        Integer currentVersion = obj.getVersion();
        Submission merged = (Submission)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Submission' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SubmissionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Submission' failed to initialize correctly", dod.getRandomSubmission());
        Submission obj = dod.getNewTransientSubmission(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Submission' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Submission' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Submission' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SubmissionIntegrationTest.testRemove() {
        Submission obj = dod.getRandomSubmission();
        Assert.assertNotNull("Data on demand for 'Submission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Submission' failed to provide an identifier", id);
        obj = Submission.findSubmission(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Submission' with identifier '" + id + "'", Submission.findSubmission(id));
    }
    
}
